[package]
name    = "zk_ecdsa"
type    = "bin"
authors = ["PinaCoDC"]

#[dependencies]

#ecrecover = { path = "./ecrecover-noir" }
#keccak256 = { git = "https://github.com/noir-lang/keccak256", tag = "v0.1.0" } // tried locally

[dependencies]
ecrecover = { tag = "v0.30.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
keccak256 = { git = "https://github.com/noir-lang/keccak256", tag = "v0.1.0" }

##sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
