[package]
name    = "zk_ecdsa_contract"
type    = "bin"
authors = [""]


[dependencies]
ecrecover = { tag = "v0.30.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
keccak256 = { git = "https://github.com/noir-lang/keccak256", tag = "v0.1.0" }
